name: Actualizar Mercados

# ¿Cuándo se ejecuta?
on:
  workflow_dispatch: # Permite darle al botón "Run" manualmente para probar
  schedule:
    - cron: '0 21 * * 1-5' # De Lunes a Viernes a las 21:00 UTC (Cierre de mercado)

# Permisos para que el robot pueda guardar cambios en tu repo
permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear código (Checkout)
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependencias
        run: |
          pip install yfinance pandas

      - name: Ejecutar Motor de Datos
        run: |
          cd data_engine
          python loader.py

      - name: Guardar y Subir Cambios (Commit & Push)
        run: |
          git config --global user.name "Market Bot"
          git config --global user.email "bot@github.com"
          git add public/market_data.json
          git commit -m "Auto-update: Precios de mercado actualizados" || echo "Sin cambios"
          git push